### ISSUE TITLE
Doesn't work with sveltekit

### ISSUE THREAD

**Issue by analubarreto** [KamyarLajani/svelte-yup#2]
I get a 500 error when I use this with sveltekit:

```
500
Unexpected token 'export'

/mnt/s/Users/analu/Documents/Projects/busybee/bProjects-web/node_modules/svelte-yup/src/index.js:1
export { default as Form } from './Form.svelte';
^^^^^^

SyntaxError: Unexpected token 'export'
    at wrapSafe (internal/modules/cjs/loader.js:979:16)
    at Module._compile (internal/modules/cjs/loader.js:1027:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at nodeRequire (/mnt/s/Users/analu/Documents/Projects/busybee/bProjects-web/node_modules/vite/dist/node/chunks/dep-6e02b235.js:69041:17)
    at ssrImport (/mnt/s/Users/analu/Documents/Projects/busybee/bProjects-web/node_modules/vite/dist/node/chunks/dep-6e02b235.js:68999:20)
    at eval (/src/lib/forms/LoginForm.svelte:15:31)
```

**Comment by KamyarLajani** [comment]
Hi Ana, Sveltik is a different library and can not be mixed with this library, svelte-yup is independent and can only be used with yup library.
